### ISSUE TITLE
How exactly is data structured and stored into keys?

### ISSUE THREAD

**Issue by athityakumar** [kigster/simple-feed#12]
I've a feed with namespace `kf` and a redis instance instance `$redis`.

```ruby
$redis.keys.select { |k| k.start_with? "kf" }.count
#=> 98

User.count
#=> 61462
```

Please let me know how I can access something like the result of  `SimpleFeed.knowledge_feed.activity(some_user_id).paginate(page: 1).map(&:value)` using my `$redis` variable. I'm imagining something like `$redis.get "appropriate key name"` or something along those lines.

**Comment by kigster** [comment]
Please check out the part of README that [talks about how to expose Redis commands](https://github.com/kigster/simple-feed#running-the-examples) that are generated by SimpleFeed.

Not having seen your code, I don't know whether `$redis` is even pointing to the same Redis instance as your SimpleFeed. 

But assuming you are talking to the correct Redis instance, I would say that you most likely did not call `store` for each and every `User` in your table, but perhaps you called it only for those users that have generated or received an event. Users that are not receiving any events via SimpleFeed would have NO feed created for them, i.e their feed would be nil.

Hope this helps.
