### ISSUE TITLE
how I can periodic export data from Redis to DB (Postgres, MySQL, etc) ?

### ISSUE THREAD

**Issue by no-cat-no** [kigster/simple-feed#2]
how I can periodic export data from Redis to DB (Postgres, MySQL, etc) ? Redis is cool, but I want to insure.

**Comment by kigster** [comment]
Right now there is no way to export data from Redis to other databases, but you can use Redis replication, or Redis Sentinel, or you can simply backup Redis RDB file periodically, and that way you will be guaranteed to have a snapshot of the data.

Honestly, Redis persistence and reliability is outside of the scope of this library, but there is a [really good post about this](https://redis.io/topics/persistence).
