### ISSUE TITLE
Release question

### ISSUE THREAD

**Issue by archonic** [kigster/simple-feed#32]
It seems every new version published is unpublishing the version that came before it. Is that intentional? The versions available through RubyGems jump from 2.1.0 to 3.1.2. It's easy enough to point to github, but every unpublished gem version in a lockfile can break a Docker build.

**Comment by kigster** [comment]
It's true, but I usually only yank versions that give blocking errors to a good number of people.

Whenever a new version is published, consider it unstable for the first few days, while error reports and fixes are coming in. After about a week the version should be considered stable and will not disappear.

**Comment by kigster** [comment]
Also - if there is a better strategy for testing beta versions I am all ears.

**Comment by archonic** [comment]
A beta tag wouldn't get much uptake so I think this strategy is fine. Thanks for the clarification 👍
