### ISSUE TITLE
Can I add a connector to use Elasticsearch?

### ISSUE THREAD

**Issue by ankitrg** [kigster/simple-feed#6]
Is there any guide on how can I make simple-feed integrate with Elasticsearch?

**Comment by kigster** [comment]
You probably can, but why? It would not be as fast as Redis and much more expensive to run.

You can simple look at the providers folder under sources and find two implementations. Copy either into a new elastic search file and then implement each API call. I'd be happy to help if you get stuck.

**Comment by ankitrg** [comment]
@kigster  Please correct me if I am wrong. Redis is supposed to use the RAM which is more costly as it seems? 
Also in case of activity stream, I would like to keep it for a longer duration of time which is limited with redis.

**Comment by kigster** [comment]
What are your requirements? Ie, number of unique users with activity feed, number of most recent items you want to store in the feed for each user (the default is 1000), and the size of the `value` — in other words, what is the item in each user's feed?

I strongly recommend that you read the wiki, in particular, this page about [serializing event stream](https://github.com/kigster/simple-feed/wiki/How-to-Store-Events-in-SimpleFeed). 

Also, you can [store the actual events in the database](https://github.com/kigster/simple-feed/wiki/Using-%60Events%60-Polymorphic-DB-Table), while storing IDs of these events in each user's feed.  This makes memory footprint of user's feed pretty small, several kilobytes at most.

ElasticSearch caches most of the data in memory anyway, so whether you use Redis or ElasticSearch, the data will be coming from RAM.

In my personal opinion, using ElasticSearch as a provider seems like an overkill — ES is a very powerful search engine, but here we'd be using it like a data store. 

Redis offers excellent performance and can scale to millions of active users. I ran activity feeds for over 10 million users using a similar architecture, which worked very well, especially when Redis backend was sharded behind a [Twemproxy](https://github.com/twitter/twemproxy).

**Comment by ankitrg** [comment]
I will explain my requirement here, it is not very traditional activity stream, but a stripped down version of it.

There is a team which has multiple accounts and they can perform actions on each of the account. Now the action performed is via the API calls which go through our back-end system. This actions can also be triggered via an automation rule created by a user of the team. This is the rough use case.

Now for auditing and security reasons we want to maintain a stream of all the activities performed by a user directly or indirectly. I also want to track if the operation was successful or not and what is the start state of an object and what is the final state of an object.

This activity log will be visible to a team on its dashboard. There are no follow/subscriber problem in my case. 

I will want to keep this feed forever(theoretically), I can use `Postgres` itself and store everything there, but I believe the volume of data is going to increase as we get more customers, I don't have enough experience to say if this can scale.

I will need the following capabilities:
- store logs for an extended period of time(non-volatile)
- fast query
- ease of cleanup(periodic archive/s3 dump for the data)

Can you give any suggestions on this?
