### ISSUE TITLE
Permissions on all .rb file are not correct

### ISSUE THREAD

**Issue by jeremybut** [kigster/simple-feed#7]
Hello,

Thanks for your work on this gem !

The permissions of the latest release uploaded to rubygems are not correct, the permissions on all .rb files are 640 instead of 644 which can cause some deployments to fail.

Could you post a new release with the correct permissions?

Best,
J.

**Comment by kigster** [comment]
OK try to reinstall the gem again. The new gem version 2.0.2 on RubyGems.org should have the correct permissions even if you are installing into system ruby.

**Comment by kigster** [comment]
```bash
❯ rake release
running: rm -rf pkg/
running: chmod -v o+r,g+r * */* */*/* */*/*/* */*/*/*/* */*/*/*/*/*
chmod: */*/*/*/*/*: No such file or directory
running: find . -type d -exec chmod o+x,g+x {} \;
simple-feed 2.0.2 built to pkg/simple-feed-2.0.2.gem.
Tagged v2.0.2.
Pushed git commits and tags.
Pushed simple-feed 2.0.2 to rubygems.org
```
